# Generated by Django 5.1.3 on 2024-12-05 17:27

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_vendor_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='cover_image',
            field=models.ImageField(default='assets/images/background-pattern.jpg', upload_to=core.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='image',
            field=models.ImageField(default='assets/images/pushpa_img.jpeg', upload_to=core.models.user_directory_path),
        ),
    ]
