# Generated by Django 5.1.3 on 2024-12-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_product_life_product_mfg_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10000000, null=True),
        ),
    ]
